### ISSUE TITLE
Curl error on quick installation

### ISSUE THREAD

**Issue by mminglis** [apisnetworks/apiscp-bootstrapper#2]
Hey, I am trying to test out this project, looks really interesting. Using a fresh Centos 7 installation on OVH, the quick installation method:

```
curl https://raw.githubusercontent.com/apisnetworks/apnscp-bootstrapper/master/bootstrap.sh | bash
```

fails with:

```
curl: (7) Failed connect to bootstrap.apnscp.com:443; Connection refused
```

**Comment by msaladna** [comment]
Resolved. Didn't install monitoring on that server 🤦‍♂️
