### ISSUE TITLE
Bootstrap still running after 3 hours

### ISSUE THREAD

**Issue by skills-up** [apisnetworks/apiscp-bootstrapper#3]
Hi,

This is the first time I'm trying APIS CP on a freshly provisioned 32GB RAM Performance+ VPS from SSD Nodes.

It has been over 3 hours and the bootstrap installation is still going on. Last task was `TASK [system/yum : Configure yum]`

There was no error except `Failure downloading http://pkg.cloudflare.com/cloudflare-release-latest.el7.rpm` but the installation continued despite the error.

Should I be worried?

**Comment by msaladna** [comment]
Duplicate of apisnetworks/apiscp#40
